const fs = require('fs').promises;
const path = require('path');
const process = require('process');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.CLIENT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: SCOPES,
});

const doc = new GoogleSpreadsheet(process.env.SPEARDSHEET_ID || '1nNkrFE4r_kkIceBN50ZI5AIKv9i6JQuk9zW70oNFYO0', serviceAccountAuth);

const addRow = async (data) => {
  await doc.loadInfo();
  const sheet = doc.sheetsByIndex[0];
  await sheet.addRow(data);
}

module.exports = { addRow };
